---
- name: Check minecraft directory
  stat:
    path: /opt/minecraft
  register: mine_dir

- name: create folder for minecraft if it doesn't exist
  file:
    path: /opt/minecraft
    state: directory
  when: not mine_dir.stat.exists

- name: Dowload Foarge installer
  get_url:
    url: https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2860/forge-1.12.2-14.23.5.2860-installer.jar
    dest: /opt/minecraft/

- name: Server Installation
  shell: java -jar forge-1.12.2-14.23.5.2860-installer.jar --installServer
  args:
    chdir: /opt/minecraft/

- name: Run minecraft server to generate files ans folders
  shell: java -Xms1024M -Xmx2000M -jar /opt/minecraft/forge-1.12.2-14.23.5.2860.jar nogui
  args:
    chdir: /opt/minecraft/

- name: Accept licence
  replace:
    path: /opt/minecraft/eula.txt
    regexp: '^(\s*eula=)false$'
    replace: '\g<1>true'

- name: Install modes
  get_url:
    url: "{{ item }}"
    dest: /opt/minecraft/mods
  loop:
    - https://media.forgecdn.net/files/3213/136/animania-1.12.2-base-2.0.3.28.jar
    - https://media.forgecdn.net/files/3613/721/DynamicTrees-1.12.2-0.9.27.jar
    - https://media.forgecdn.net/files/2661/859/CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar
    - https://media.forgecdn.net/files/3213/139/animania-1.12.2-farm-1.0.2.28.jar

- name: Run minecraft server
  shell: java -Xms1024M -Xmx2000M -jar /opt/minecraft/forge-1.12.2-14.23.5.2860.jar nogui
  args:
    chdir: /opt/minecraft/
