---
- name: Check minecraft directory
  stat:
    path: "{{ mine_home }}"
  register: mine_dir

- name: create folder for minecraft if it doesn't exist
  file:
    path: "{{ mine_home }}"
    state: directory
  when: not mine_dir.stat.exists

- name: Dowload Foarge installer
  get_url:
    url: "{{ forge_server }}"
    dest: "{{ mine_home }}/{{ server_installer }}"

- name: Server Installation
  shell: java -jar {{ server_installer }} --installServer
  args:
    chdir: "{{ mine_home }}"
  
- name: Find file
  find:
    path: "{{ mine_home }}"
    file_type: file
    use_regex: true
    patterns: "^(forge)"
  register: find_res

- name: name of server
  set_fact:
    file_to_start_server: "{{ find_res.files | map(attribute='path') | first | basename}}"
  
- name: Run minecraft server to generate files ans folders
  shell: "java -Xms1024M -Xmx2000M -jar {{ file_to_start_server }} nogui"
  args:
    chdir: "{{ mine_home }}"

- name: Accept licence
  replace:
    path: "{{ mine_home }}/eula.txt"
    regexp: '^(\s*eula=)false$'
    replace: '\g<1>true'

- name: Install modes
  get_url:
    url: "{{ item }}"
    dest: "{{ mine_home }}/mods"
  loop:
    "{{ mods }}"

# Command below will run server after installation but you won't be able to access server terminal
# - name: Run minecraft server
#   shell: "java -Xms1024M -Xmx2000M -jar {{ mine_home }}/forge-1.12.2-14.23.5.2860.jar nogui"
#   args:
#     chdir: "{{ mine_home }}"
