---
- name: Update and upgrade apt packages
  hosts: minecraft
  gather_facts: true
  become: true

  tasks:
    - apt:
        upgrade: true
        update_cache: true
  

- name: Configure Minecraft server with mods
  hosts: minecraft
  gather_facts: true
  become: true
  
  roles:
    
    - name: Install Java 8
      role: java_8

    - name: Configure minecraft server
      role: mine_serv
