---
- name: Update and upgrade apt packages
  hosts: minecraft
  gather_facts: true
  become: true

  tasks:
    - apt:
        upgrade: true
        update_cache: true

    - name: Install Java 8
      import_role:
        name: java_8

    - name: Configure minecraft server
      import_role:
        name: mine_serv
